openapi: 3.0.3
info:
  title: CRUD API
  description: A RESTful CRUD API built with Vert.x and MongoDB
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8888
    description: Development server

paths:
  /api/v1/hello:
    get:
      summary: Health check endpoint
      description: Check if the API is running
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "API is up and running!"

  /api/v1/resources:
    get:
      summary: Get all resources
      description: Retrieve all resources with optional filtering and pagination
      parameters:
        - name: filter
          in: query
          description: Filter resources (format field:value)
          required: false
          schema:
            type: string
            example: "name:example"
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            example: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Resource"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Create a new resource
      description: Create a new resource in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResourceInput"
            example:
              name: "Example Resource"
              description: "This is an example resource"
              category: "example"
      responses:
        "201":
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/resources/{id}:
    get:
      summary: Get a resource by ID
      description: Retrieve a specific resource by its ID
      parameters:
        - name: id
          in: path
          required: true
          description: Resource ID
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "400":
          description: Invalid ID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Update a resource completely
      description: Replace all fields of a resource
      parameters:
        - name: id
          in: path
          required: true
          description: Resource ID
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResourceInput"
            example:
              name: "Updated Resource"
              description: "This resource has been updated"
              category: "updated"
      responses:
        "200":
          description: Resource updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "400":
          description: Invalid ID format or bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      summary: Partially update a resource
      description: Update specific fields of a resource
      parameters:
        - name: id
          in: path
          required: true
          description: Resource ID
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
            example:
              name: "Partially Updated Resource"
      responses:
        "200":
          description: Resource updated successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        "400":
          description: Invalid ID format or bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Delete a resource
      description: Remove a resource from the database
      parameters:
        - name: id
          in: path
          required: true
          description: Resource ID
          schema:
            type: integer
            example: 1
      responses:
        "204":
          description: Resource deleted successfully
        "400":
          description: Invalid ID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Resource:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the resource
          example: 1
        name:
          type: string
          description: Name of the resource
          example: "Example Resource"
        description:
          type: string
          description: Description of the resource
          example: "This is an example resource"
        category:
          type: string
          description: Category of the resource
          example: "example"
        _id:
          type: string
          description: MongoDB document ID
          example: "64f1234567890abcdef12345"
      required:
        - id
        - name

    ResourceInput:
      type: object
      properties:
        name:
          type: string
          description: Name of the resource
          example: "Example Resource"
        description:
          type: string
          description: Description of the resource
          example: "This is an example resource"
        category:
          type: string
          description: Category of the resource
          example: "example"
      required:
        - name

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Resource not found"
      required:
        - error

    PaginatedResponse:
      type: object
      properties:
        page:
          type: integer
          description: Current page number
          example: 1
        limit:
          type: integer
          description: Number of items per page
          example: 10
        total:
          type: integer
          description: Total number of items
          example: 100
        data:
          type: array
          items:
            $ref: "#/components/schemas/Resource"
          description: Array of resources
      required:
        - page
        - limit
        - total
        - data
